name: lolmeet
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get:
  get_storage: ^2.0.3
  flutter:
    sdk: flutter
  
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1
  firebase_messaging: ^10.0.4
  firebase_analytics: ^8.2.0
  cloud_firestore: ^2.4.0
  awesome_notifications: ^0.0.6+10
  google_fonts: ^2.1.0
  flutter_native_splash: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/backgrounds/
    - assets/icons/
    - assets/logo/

flutter_native_splash:
  color: "#0B1C26"
  image: assets/logo/splash_logo.png    
 